language:
  ruby
notifications:
  email:
    on_success: always
script:
  - 'bundle exec rake test'
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
